//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/Input/DefaultInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DefaultInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DefaultInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DefaultInput"",
    ""maps"": [
        {
            ""name"": ""Input"",
            ""id"": ""b1b4c2e8-7f81-49fd-97f0-f3f3506bd762"",
            ""actions"": [
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""0f863293-21d0-42b2-a661-498aded324b3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""bfc0e2b1-7ed6-4fd3-acf0-58b8fdce4ba6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseScroll"",
                    ""type"": ""Value"",
                    ""id"": ""686e86cc-929c-48c5-b706-edb56877b426"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseSelect"",
                    ""type"": ""Button"",
                    ""id"": ""d25a7a99-e96d-458a-bb99-62e0a4712a70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDeselect"",
                    ""type"": ""Button"",
                    ""id"": ""32158a17-e392-4620-b24b-71745a225a5c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""KeyboardLeft"",
                    ""type"": ""Button"",
                    ""id"": ""1a695a23-97a2-451b-b0a3-b88f56999814"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""KeyboardRight"",
                    ""type"": ""Button"",
                    ""id"": ""6ecf4a3c-f42d-4b84-bc87-133060b1a746"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""KeyboardUp"",
                    ""type"": ""Button"",
                    ""id"": ""d2ff467d-b357-4926-ae65-d1e2a40b2dcc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""KeyboardDown"",
                    ""type"": ""Button"",
                    ""id"": ""86b8e842-0093-4642-a438-2cadde8f1a09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""KeyboardConfirm"",
                    ""type"": ""Button"",
                    ""id"": ""3172984c-35b4-4229-9fe8-55ae0401c01e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""KeyboardCancel"",
                    ""type"": ""Button"",
                    ""id"": ""55b39fff-dbf0-4110-82b8-1266342e8d25"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""KeyboardNavigation"",
                    ""type"": ""Value"",
                    ""id"": ""af51de19-e81f-4130-92d0-473af7742652"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""080c2986-9616-4442-ba24-4007590e24b4"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3148e9a4-1b40-4c5d-8dc0-52b120af2276"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c26996df-418d-4114-9c34-8e0f376892e1"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDeselect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a157473d-c159-4102-ad0d-6d48de45ddd7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""473041d7-44ed-46a4-9247-1c2feb77a1f8"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61dace81-dd63-4cda-b500-10bbc0c66fba"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cf11f31-5f78-4119-a158-6132dc008a35"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2beb6ac-c9a3-4cf3-bdf0-5cc49a6c9018"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b284e7d2-60fd-4dc8-82bc-c9f266d2ad3e"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d223db6-7d40-4f62-bf5e-45a87701c9c7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ca7fbf0-716a-4e1b-b388-c148913f5312"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""528f4eef-d85f-4f90-ac66-32d85c6c1f45"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardCancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba45ab71-e9ee-4923-890e-f65797c6b007"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbc38d42-6c6d-4270-a42b-258d421e88b8"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a12ad1b-e355-483c-b3f1-fffead60f4e0"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""51a28457-2779-4ff4-8a23-6127cdd5cbab"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardNavigation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6a6b7f8a-a662-49b5-afa1-900490b9fdb2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""df7a6361-bae9-4cc4-bc10-31b84d14ada3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""adc77562-a02a-4910-913c-6995f56f3ea9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cd1c3dd1-2bfe-4367-b6fc-20235d7808e8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""29ca1e2e-15cb-4ad0-914f-028f8116345c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardNavigation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e9cbfdb9-9938-4fed-b1e1-c8acb8b876ff"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b762ad3a-10a7-4872-ba18-e4c1485f6349"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0227cb39-364e-4f01-b981-6884947dfe9b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3ba99973-f9ac-43e4-a3d4-243fde1ebadd"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Input
        m_Input = asset.FindActionMap("Input", throwIfNotFound: true);
        m_Input_MousePosition = m_Input.FindAction("MousePosition", throwIfNotFound: true);
        m_Input_MouseDelta = m_Input.FindAction("MouseDelta", throwIfNotFound: true);
        m_Input_MouseScroll = m_Input.FindAction("MouseScroll", throwIfNotFound: true);
        m_Input_MouseSelect = m_Input.FindAction("MouseSelect", throwIfNotFound: true);
        m_Input_MouseDeselect = m_Input.FindAction("MouseDeselect", throwIfNotFound: true);
        m_Input_KeyboardLeft = m_Input.FindAction("KeyboardLeft", throwIfNotFound: true);
        m_Input_KeyboardRight = m_Input.FindAction("KeyboardRight", throwIfNotFound: true);
        m_Input_KeyboardUp = m_Input.FindAction("KeyboardUp", throwIfNotFound: true);
        m_Input_KeyboardDown = m_Input.FindAction("KeyboardDown", throwIfNotFound: true);
        m_Input_KeyboardConfirm = m_Input.FindAction("KeyboardConfirm", throwIfNotFound: true);
        m_Input_KeyboardCancel = m_Input.FindAction("KeyboardCancel", throwIfNotFound: true);
        m_Input_KeyboardNavigation = m_Input.FindAction("KeyboardNavigation", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Input
    private readonly InputActionMap m_Input;
    private List<IInputActions> m_InputActionsCallbackInterfaces = new List<IInputActions>();
    private readonly InputAction m_Input_MousePosition;
    private readonly InputAction m_Input_MouseDelta;
    private readonly InputAction m_Input_MouseScroll;
    private readonly InputAction m_Input_MouseSelect;
    private readonly InputAction m_Input_MouseDeselect;
    private readonly InputAction m_Input_KeyboardLeft;
    private readonly InputAction m_Input_KeyboardRight;
    private readonly InputAction m_Input_KeyboardUp;
    private readonly InputAction m_Input_KeyboardDown;
    private readonly InputAction m_Input_KeyboardConfirm;
    private readonly InputAction m_Input_KeyboardCancel;
    private readonly InputAction m_Input_KeyboardNavigation;
    public struct InputActions
    {
        private @DefaultInput m_Wrapper;
        public InputActions(@DefaultInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @MousePosition => m_Wrapper.m_Input_MousePosition;
        public InputAction @MouseDelta => m_Wrapper.m_Input_MouseDelta;
        public InputAction @MouseScroll => m_Wrapper.m_Input_MouseScroll;
        public InputAction @MouseSelect => m_Wrapper.m_Input_MouseSelect;
        public InputAction @MouseDeselect => m_Wrapper.m_Input_MouseDeselect;
        public InputAction @KeyboardLeft => m_Wrapper.m_Input_KeyboardLeft;
        public InputAction @KeyboardRight => m_Wrapper.m_Input_KeyboardRight;
        public InputAction @KeyboardUp => m_Wrapper.m_Input_KeyboardUp;
        public InputAction @KeyboardDown => m_Wrapper.m_Input_KeyboardDown;
        public InputAction @KeyboardConfirm => m_Wrapper.m_Input_KeyboardConfirm;
        public InputAction @KeyboardCancel => m_Wrapper.m_Input_KeyboardCancel;
        public InputAction @KeyboardNavigation => m_Wrapper.m_Input_KeyboardNavigation;
        public InputActionMap Get() { return m_Wrapper.m_Input; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InputActions set) { return set.Get(); }
        public void AddCallbacks(IInputActions instance)
        {
            if (instance == null || m_Wrapper.m_InputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InputActionsCallbackInterfaces.Add(instance);
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @MouseDelta.started += instance.OnMouseDelta;
            @MouseDelta.performed += instance.OnMouseDelta;
            @MouseDelta.canceled += instance.OnMouseDelta;
            @MouseScroll.started += instance.OnMouseScroll;
            @MouseScroll.performed += instance.OnMouseScroll;
            @MouseScroll.canceled += instance.OnMouseScroll;
            @MouseSelect.started += instance.OnMouseSelect;
            @MouseSelect.performed += instance.OnMouseSelect;
            @MouseSelect.canceled += instance.OnMouseSelect;
            @MouseDeselect.started += instance.OnMouseDeselect;
            @MouseDeselect.performed += instance.OnMouseDeselect;
            @MouseDeselect.canceled += instance.OnMouseDeselect;
            @KeyboardLeft.started += instance.OnKeyboardLeft;
            @KeyboardLeft.performed += instance.OnKeyboardLeft;
            @KeyboardLeft.canceled += instance.OnKeyboardLeft;
            @KeyboardRight.started += instance.OnKeyboardRight;
            @KeyboardRight.performed += instance.OnKeyboardRight;
            @KeyboardRight.canceled += instance.OnKeyboardRight;
            @KeyboardUp.started += instance.OnKeyboardUp;
            @KeyboardUp.performed += instance.OnKeyboardUp;
            @KeyboardUp.canceled += instance.OnKeyboardUp;
            @KeyboardDown.started += instance.OnKeyboardDown;
            @KeyboardDown.performed += instance.OnKeyboardDown;
            @KeyboardDown.canceled += instance.OnKeyboardDown;
            @KeyboardConfirm.started += instance.OnKeyboardConfirm;
            @KeyboardConfirm.performed += instance.OnKeyboardConfirm;
            @KeyboardConfirm.canceled += instance.OnKeyboardConfirm;
            @KeyboardCancel.started += instance.OnKeyboardCancel;
            @KeyboardCancel.performed += instance.OnKeyboardCancel;
            @KeyboardCancel.canceled += instance.OnKeyboardCancel;
            @KeyboardNavigation.started += instance.OnKeyboardNavigation;
            @KeyboardNavigation.performed += instance.OnKeyboardNavigation;
            @KeyboardNavigation.canceled += instance.OnKeyboardNavigation;
        }

        private void UnregisterCallbacks(IInputActions instance)
        {
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @MouseDelta.started -= instance.OnMouseDelta;
            @MouseDelta.performed -= instance.OnMouseDelta;
            @MouseDelta.canceled -= instance.OnMouseDelta;
            @MouseScroll.started -= instance.OnMouseScroll;
            @MouseScroll.performed -= instance.OnMouseScroll;
            @MouseScroll.canceled -= instance.OnMouseScroll;
            @MouseSelect.started -= instance.OnMouseSelect;
            @MouseSelect.performed -= instance.OnMouseSelect;
            @MouseSelect.canceled -= instance.OnMouseSelect;
            @MouseDeselect.started -= instance.OnMouseDeselect;
            @MouseDeselect.performed -= instance.OnMouseDeselect;
            @MouseDeselect.canceled -= instance.OnMouseDeselect;
            @KeyboardLeft.started -= instance.OnKeyboardLeft;
            @KeyboardLeft.performed -= instance.OnKeyboardLeft;
            @KeyboardLeft.canceled -= instance.OnKeyboardLeft;
            @KeyboardRight.started -= instance.OnKeyboardRight;
            @KeyboardRight.performed -= instance.OnKeyboardRight;
            @KeyboardRight.canceled -= instance.OnKeyboardRight;
            @KeyboardUp.started -= instance.OnKeyboardUp;
            @KeyboardUp.performed -= instance.OnKeyboardUp;
            @KeyboardUp.canceled -= instance.OnKeyboardUp;
            @KeyboardDown.started -= instance.OnKeyboardDown;
            @KeyboardDown.performed -= instance.OnKeyboardDown;
            @KeyboardDown.canceled -= instance.OnKeyboardDown;
            @KeyboardConfirm.started -= instance.OnKeyboardConfirm;
            @KeyboardConfirm.performed -= instance.OnKeyboardConfirm;
            @KeyboardConfirm.canceled -= instance.OnKeyboardConfirm;
            @KeyboardCancel.started -= instance.OnKeyboardCancel;
            @KeyboardCancel.performed -= instance.OnKeyboardCancel;
            @KeyboardCancel.canceled -= instance.OnKeyboardCancel;
            @KeyboardNavigation.started -= instance.OnKeyboardNavigation;
            @KeyboardNavigation.performed -= instance.OnKeyboardNavigation;
            @KeyboardNavigation.canceled -= instance.OnKeyboardNavigation;
        }

        public void RemoveCallbacks(IInputActions instance)
        {
            if (m_Wrapper.m_InputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInputActions instance)
        {
            foreach (var item in m_Wrapper.m_InputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InputActions @Input => new InputActions(this);
    public interface IInputActions
    {
        void OnMousePosition(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnMouseScroll(InputAction.CallbackContext context);
        void OnMouseSelect(InputAction.CallbackContext context);
        void OnMouseDeselect(InputAction.CallbackContext context);
        void OnKeyboardLeft(InputAction.CallbackContext context);
        void OnKeyboardRight(InputAction.CallbackContext context);
        void OnKeyboardUp(InputAction.CallbackContext context);
        void OnKeyboardDown(InputAction.CallbackContext context);
        void OnKeyboardConfirm(InputAction.CallbackContext context);
        void OnKeyboardCancel(InputAction.CallbackContext context);
        void OnKeyboardNavigation(InputAction.CallbackContext context);
    }
}
